cmd/drive/main.go, config/config.go, diff.go
init: Cleanup if authorization is aborted
Scenarios for if the init authorization is cancelled:
+ Init has been invoked in this directory before,
in this case do nothing.
+ This is the first initializing, in this case cleanup.
=> init: Cleanup if authorization is aborted

src/changes.go, src/help.go, src/pull.go, src/push.go, src/types.go
+ Abort on detection of clobbering.
+ Use the force flag to override this behaviour.
This is meant to address issue #57
=> naive conflict resolution: abort on conflict detection

README.md, cmd/drive/main.go, src/commands.go, src/pull.go, src/push.go, src/remote.go, src/types.go
This PR addresses feature request https://github.com/odeke-em/drive/issues/62.
It allows for content to be piped from stdin to a path e.g
```shell
$ cat banx/Makefile | drive push -piped foxy.txt
```
```shell
$ drive pull -piped names.txt > ~/Desktop/records/names.txt
```
Since this code contains source that caused #68 PR #69's code is needed to integrate so as to avoid the noise from ".gd/credentials.json" path not found. The hardcore can just keep removing the ".gd/indices" files and keep testing out this code.
=> piping: support stdin and stdout sources

README.md, cmd/drive/main.go, src/changes.go, src/commands.go, src/help.go, src/pull.go, src/push.go
This flag is necessary to handle conflicts as opposed to
using -force which instead would push everything.
This PR addresses #66
=> ignore-conflict flag added

README.md, src/changes.go, src/commands.go, src/misc.go, src/push.go
A work in progress to address #82.
A .driveignore file should be placed at the root of the drive. A sample file is:
```shell
.swp
.so
heap
.keys
```
=> .driveignore started, similar to a .gitignore file

src/push.go, src/remote.go
Always insert media on push piped since stating os.Stdin
is meaningless. The completes the fix for #87.
=> nonStatable push.piped

src/push.go
Addresses issue #80 and fixes commit 7f7dea574c30eb35f1276c38b3204a2d86f0e783. The proper path of the symlink is now used
=> list: traverse nested dir symlinks

src/changes.go, src/pull.go, src/push.go
+ Fix mistyped 'push' toggle that was alway set to true
irrespective of type of op: push vs pull.
+ Check if indexed.ModTime == dest.ModTime on push.
This PR is meant to address #114 for which a bug manifested because the last indexTime was not being checked against the destination modTime as well as a mistyped 'push' toggle.
=> resolveConflict: push toggle, indexVsdestTime cmp

src/commands.go
The new quiet mode will break things if no options are used. This fixes it by only checking for opts.quiet if opts != nil.
=> don't dereference Opts if nil

src/commands.go, src/list.go, src/misc.go, src/pull.go, src/push.go, src/share.go, src/trash.go
Use case is for example when using drive as output to another process
e.g
`drive list openSrc | wc`
This PR is meant to address #119
=> disable pagination and prompting if stdout !isatty

README.md, cmd/drive/main.go, src/changes.go, src/list.go, src/pull.go
Adds the ability to list as well as pull by matches e.g:
```shell
$ cd ~/mydrive/openSrc/wordSuggestions
$ drive list --matches png
```
```shell
$ cd ~/mydrive/documents
$ drive pull --matches docx png go
```
=> matches for pull + list in

src/help.go
Provide by default information like Go version, commit hash,
OS which is usually neglected during bug reports and has
to be reminded to the issue reporters.
This PR is meant to address issue https://github.com/odeke-em/drive/issues/138
Sample output
=> about/help: provide more diagnostic information

src/changes.go, src/commands.go, src/pull.go, src/push.go, src/remote.go, src/trash.go
Allows for constant updates byte by byte to shown.
This fixes the old style of progress reporting that
would only update once a job was completed. Previously
could not work for large jobs.
This PR addresses issues https://github.com/odeke-em/drive/issues/108 and https://github.com/odeke-em/drive/issues/23
=> progress: byte by byte progress info.

README.md, cmd/drive/main.go, src/help.go
This PR addresses issue https://github.com/odeke-em/drive/issues/136.
Makes usage familiar with that in your shell e.g
```shell
$ drive cp vines videos
$ drive copy vines videos
```
OR
```shell
$ drive ls content
$ drive list content
```
OR
```shell
$ drive mv focus angeles/los
$ drive move focus angeles/los
```
=> command aliases added in

README.md, cmd/drive/main.go, src/changes.go, src/help.go, src/misc.go, src/push.go, src/remote.go
This is a patch to handle issue #154 in which failure to preprocess mimeTypes leads drive to create archive files for *.doc files. The changes in this PR will entail coercing the mimeType if the user decides so i.e
```shell
$ drive push --coerced-mime docx test_doc.docx
```
This PR also allows for mimeType inference from extensions e.g
```shell
$ drive push tests.docx
```
```shell
$ drive stat test_doc.docx
/test_doc.docx
...                   
MimeType             application/zip  
```
```shell
$ driv stat test_doc.docx
/test_doc.docx
MimeType             application/vnd.openxmlformats-officedocument.wordprocessingml.document
```
=> Coerced mime type

src/misc.go, src/trash.go, src/tty.go, src/tty_nocgo.go
Requires cgo to work, and it only works on Unix.
Fixes #157.
=> flush tty input buffer before asking users for decisions

README.md, cmd/drive/main.go, src/changes.go, src/commands.go, src/help.go, src/pull.go
This is a work in progress to address the issue of name clashes within the same directory. This is because Google Drive allows same-name-different-files within the same folder.
This is meant to address issue https://github.com/odeke-em/drive/issues/107
=> clashes: detect and abort on clashes if can

README.md, cmd/drive/main.go, src/help.go, src/misc.go, src/push.go, src/remote.go, src/trash.go
This PR implements the `delete` method to address issue https://github.com/odeke-em/drive/issues/164.
Sample usage:
```shell
emmanuel@lap:~/emm.odeke.drive$ drive push --hidden --force .edits.swp 
Resolving...
+ /.edits.swp
Addition count 1 src: 23.89KB
Proceed with the changes? [Y/n]:y
24459 / 24459 [====================================================] 100.00 % 1s
emmanuel@lap:~/emm.odeke.drive$ drive delete --matches .edits.swp
- /.edits.swp
Deletion count 1 dest: 23.89KB
Proceed with the changes? [Y/n]:n
emmanuel@lap:~/emm.odeke.drive$ drive delete .edits.swp
- /.edits.swp
Deletion count 1 dest: 23.89KB
Proceed with the changes? [Y/n]:n
emmanuel@lap:~/emm.odeke.drive$ drive delete --matches .swp
- /.edits.swp
Deletion count 1 dest: 23.89KB
Proceed with the changes? [Y/n]:y
24459 / …
```
=> delete: implemented

README.md, cmd/drive/main.go
This is because checksum verification by default was deemed to be
too vigorous and unncessary by default. This discussion stems from
issue #117.
=> ignoreChecksum: true by default

README.md, cmd/drive/main.go, gen/generated.go, src/about.go, src/generated.go, src/help.go
Now has the ability to bundle static information at build time. However changes the build process to be (extract the current repo information and generate the appropriate files then build drive)
```shell
$ go get -u github.com/odeke-em/drive-gen && drive-gen
```
Instead of
```shell
$ go get -u github.com/odeke-em/drive/cmd/drive
```
This PR is meant to address https://github.com/odeke-em/drive/issues/138.
=> Static build

README.md, cmd/drive/main.go, src/changes.go, src/commands.go, src/help.go, src/misc.go, src/push.go, src/types.go
This PR is meant to address issue https://github.com/odeke-em/drive/issues/169 and adds the ability to exclude certain operations e.g say you only want create ops or create and delete
```shell
$ drive pull --exclude-ops "delete,create"
$ drive push --exclude-ops "update,delete"
```
=> exclude-ops for pull/push added

src/commands.go
Dear Odeke,
thanks for continuing the development of this software! The following pull request is a solution to the problem of having an empty `.driveignore` file in the root initiated folder. When running this from a (drive) root folder:
```
rm -f .driveignore && touch .driveignore
drive pull
```
Then, the following (error) message occurs:
```
Resolving...
| 
'/' is set to be ignored yet is being processed. Use `force` to override this
```
I assume the following:
* `readCommentedFile` in `misc.go` returns a `[]string`, which has length zero.
* `readCommentedFileCompileRegexp` in `commands.go` then joins it, separated by `|`, returning an empty, compiled string.
* `resolveToLocalFile` in `changes.go` matches the compiled expression `""` against `relToRoot` which is `"/"`
So a zero length …
=> ignore empty .driveignore

src/pull.go
This PR addresses issue #177 in which the byte count of exported
files is not known before hand or in the manifest but found
at export time.  The issue was that the size of exportable files is not known and hence cannot be put into a manifest for the byte counter. However on every download completion, the byte count was submitted to the progress meter.
=> pull: provide download arg for byte progress ack.

src/push.go
Retain the original name as it appeared in the manifest
This fixes issue #183.
=> push.list: for symlink retain name as in manifest

config/config.go
This PR addresses issue #161
no gd context is found; use gd init
no drive context found; run drive inside one of the directories (sub directories) that you performed `drive init`
=> init: better error msg for no drive context

src/commands.go, src/help.go, src/misc.go, src/pull.go
This PR is a work in progress to address issue https://github.com/odeke-em/drive/issues/165
* Make desktop entries executable on pulling.
* Add .desktop to every pulled exportable file.
To test it out
```shell
$ go get github.com/odeke-em/drive/cmd/drive
$ cd $GOPATH/src/github.com/odeke-em/drive && git fetch --all
$ git checkout desktop-links && go get github.com/odeke-em/drive/cmd/drive
```
or read on how to apply patches here https://github.com/odeke-em/drive#applying-patches
=> add .desktop ext for exportables + make executable

README.md, cmd/drive/main.go, src/copy.go, src/help.go, src/list.go, src/move.go, src/publish.go, src/pull.go, src/share.go, src/stat.go, src/touch.go, src/trash.go, src/types.go
This PR addresses issue https://github.com/odeke-em/drive/issues/190
that is operations by id.
- [+] diff by id -- Won't be implemented
- [+]  push by id -- Won't be implemented
=> operations by id

src/changes.go, src/list.go, src/remote.go, src/trash.go
This PR addresses issue #204.
What happened is that for emptyTrash, a wrong child count was being returned.
=> emptyTrash: no need to paginate + track pagination result

README.md, src/changes.go, src/push.go, src/remote.go
This PR addresses issue #208 because:
Reading from a named pipe with no content will hang
infinitely until content is passed in.
Simple test here:
```shell
$ fifoPath=testPipe
$ mkfifo $fifoPath
$ sleeper() { i=0;while [ $i -lt 20 ];do echo -e "sleeping $i\r"; let
i=i+1;sleep 1;done; echo "done here $i" >> $fifoPath; }
$ sleeper & # Put it in the background
$ cat $fifoPath # Going to hang for the 20 seconds -- this can happen
infinitely
```
=> namedPipe: reject namedPipes when listing

src/misc.go, src/pull.go, src/remote.go
This PR addresses issue #217 where http.Get returns a nil response on err yet the response was always dereferenced without check. The issue was identified, and investigated + basically solved by @sselph who unfortunately couldn't make a PR asap till over the week. This PR is representative of @sselph's tracking. It also handles the case in a file doesn't exist remotely and is forced to be pulled locally.
=> avoid nil dereferences for http.Get() + serialize

cmd/drive/main.go, src/help.go
* Fixes #45 by setting a custom usage function
* Also allows for multiple topics to be selected
on `drive --help/help/-h [topics...]
Involved patching the flag parser lib externally.
```shell
$ drive --help
Usage of drive:
$
$ drive -h
Usage of drive:
```
```shell
$ drive -h push
Name
push - push local changes to Google Drive
Description
Uploads content to your Google Drive from your local path
Push comes in a couple of flavors
* Ordinary push: `drive push path1 path2 path3`
* Mounted push: `drive push -m path1 [path2 path3] drive_context_path`
Note: You can skip checksum verification by passing in flag `-ignore-checksum`
* For usage flags: `drive push -h`
$
$ drive --help pull push
Name
pull - pulls remote changes from Google Drive
Description
Downloads content from the remote drive or …
```
=> help: allow for variants of -h, --help

src/init.go, src/remote.go
This PR addresses issues https://github.com/odeke-em/drive/issues/110 and https://github.com/odeke-em/drive/issues/116.
It uses the new shiny lib golang/x/* and thus gets rid of any previous needs for mercurial, everything is now git based. Also with the maintained and fixed re-write x/oauth2 we'll hopefully be auto refreshing of tokens on expiration.
=> oauth2 migration to golang/x new lib

README.md, cmd/drive/main.go, src/help.go, src/list.go, src/misc.go, src/sort.go
This PR implements sorting and addresses issue https://github.com/odeke-em/drive/issues/40.
It implements multi field sorting as well as reverse order sorting e.g
* To first sort by modTime, then largest-to-smallest and finally most number of saves:
```
$ drive list --sort modtime,size_r,version_r Photos
```
OR
```
$ drive list --sort modtime,size-,version- Photos
```
OR the same command but in reverse
```
$ drive list --sort modtime_r,size,version Photos
```
=> sort implemented!

cmd/drive/main.go
This PR addresses issue #233 by introducing the `ignore-conflict` flag.
=> diffCmd: added ignore-conflict option

.travis.yml, README.md, cmd/drive/main.go, src/help.go, src/list.go, src/misc.go, src/pull.go, src/remote.go, src/touch.go, src/trash.go, src/types.go
This PR addresses issue #242.
Added extra search options for list e.g:
```shell
$ drive list --skip-mime mp4,doc,txt
$ drive list --match-mime xls,docx
$ drive list --exact-title url_test,Photos
```
This sets the ground work for other search options to be added in the future.
=> Improved search for listing

src/changes.go, src/diff.go, src/pull.go, src/push.go
This PR addresses issues https://github.com/odeke-em/drive/issues/222 and duplicate https://github.com/odeke-em/drive/issues/241
* Properly detects clashes as far as can be traversed and
also warning the user if any exist or aborting.
=> clashes: properly detecting clashes & warnings

README.md, cmd/drive/main.go, src/help.go, src/misc.go, src/new.go, src/remote.go
This PR addresses issue #245.
It allows for creation of new file or folders e.g
```shell
$ drive new --folder flux
$ drive new --mime-key doc bofx
$ drive new --mime-key folder content
$ drive new flux.txt oxen.pdf # Allow auto type resolution from the extension
```
=> New file or folder

src/sort.go
Tiny bug - sorting in reverse order not working. 
Before this fix:
````
michael@taygetos:~/GoogleDrive/test2$ drive ls -l -sort size-
-- owner       6.00B     	0B7L9Xx9YIQk9ODJfV2EwMG16RDA		2015-06-26 11:26:26 +0000 UTC	/test2/file4                                      
-- owner       45.00B    	0B7L9Xx9YIQk9M2t2WU1McEd6QlE		2015-06-26 11:25:39 +0000 UTC	/test2/file1                                      
-- owner       31.00B    	0B7L9Xx9YIQk9V2pjRnlIOV82c1k		2015-06-26 11:23:09 +0000 UTC	/test2/file3                                      
-- owner       13.00B    	0B7L9Xx9YIQk9dW4zSWphcHhJM0k		2015-06-26 11:23:02 +0000 UTC	/test2/file2                                      
````
After this fix:
````
michael@taygetos:~/GoogleDrive/test2$ drive ls -l -sort size-
-- owner       45.00B …
```
=> Reverse order sort not working

src/push.go, src/remote.go
This PR addresses some issues found out in #250 in particular:
* Acknowledge errors encountered during mkdirAll or push and abort since mostly
not yet looking at retryable errors.
* Fixed up order of checking for retryFile in mkdirAll
instead of checking if err != ErrPathNotExists yet err
could be nil. This is fatal because in combination with ignored errors,
it inaccurately reports that a folder doesn't exist.
=> push: acknowledge mkdirAll errors + bug fix

src/misc.go, src/push.go
This PR addresses issue https://github.com/odeke-em/drive/issues/270
ignore pattern checks should operate on full resolved
paths instead of only the basename of paths. This applies
to resolved paths for symlinks as well.
=> ignore-check: use fullPath vs only basename

src/move.go, src/pull.go
This PR addresses issue #275 and in particular it does:
* Handle cases when files are missing remotely but present
locally, in this case the FileId is always empty.
* Provide error message when a move's src == dest.
=> index-handling and move error fixes

README.md, drive-gen/build.go, gen/generated.go, google-drive/main.go
This PR addresses issues #271 and #277 
This allows for folks that might need different binary names to
have them. For example:
`go get -u github.com/odeke-em/drive/google-drive`
OR
`
go get -u github.com/odeke-em/drive/drive-gen &&
drive-gen google-drive
`
=> provide different binary name for Debian

README.md, cmd/drive/main.go, config/config.go, src/help.go, src/init.go
This PR addresses issue #282 by adding `deinit` functionality.
```shell
$ drive deinit
```
OR
```shell
$ drive deinit --no-prompt
```
Paired with the sections on uninstalling and revoking account access, this should give the user total control of their account.
=> deinit command + info added

src/misc.go
This PR addresses issue #289. In particular
+ Fixes the mimeType for sheet to .spreadsheet from .sheet.
+ Also adds in mimeTypes for Google presentations + scripts.
```shell
$ cd ~/your_drive
$ drive new --mime-key sheet tables
/tables: googleapi: Error 400: Invalid mime type provided, invalid
```
```shell
$ cd ~/your_drive
$ drive new --mime-key sheet tables
/tables ML5VWnlKvLf71GYdBjIMG96lxCpjMBFNPISHKF3Uy4X2
$ drive list -l tables
0.00B         ML5VWnlKvLf71GYdBjIMG96lxCpjMBFNPISHKF3Uy4X2 	2015-07-19 03:58:18 +0000 UTC	/tables 
```
=> fix mimeType for sheet + add other mimes

cmd/drive/main.go
This PR addresses issue #294 by ensuring that if `drive about` is invoked with no sub set commands it prints out all information otherwise a user would have to read the manual, yet this is isn't necessary.
=> about: provide all subset commands if no subcmd set

src/changes.go, src/types.go
This PR addresses issue #292.
Since os specific export files are created, allow for inclusion of
these aliases e.g Google Docs on Linux get exported to *.desktop,
*.desktop files should be recognized too
=> os centric aliases per file

src/pull.go
Touching the original path for exportable files ensures
that on Linux on which a *.desktop is created instead, any
path mismatches won't be made on later pulls/pushes.
This PR addresses #306 
To test it out:
```shell
$ cd $GOPATH/src/github.com/odeke-em/drive
$ git fetch --all && git checkout always-touch-orig-exportable-file
$ go get github.com/odeke-em/drive/cmd/drive
```
=> exportable files: always touch orig path

drive-gen/build.go, src/misc.go
+ Revert virgin gen/generated.go after building the binary
to ensure that no conflicts are created in the repo later.
+ Package BuildTime into binary.
+ Fix error logged in case of generated file write fail.
=> drive-gen: revert gen/generated file after build

src/pull.go, src/remote.go, src/types.go
This PR fixes exporting. It was broken by commit https://github.com/odeke-em/drive/commit/787e7f03bdba2ec00cc9da558ca8a47781a7b975 in PR https://github.com/odeke-em/drive/pull/307
In particular this PR:
+ Fixed up exporting of Google Docs + Sheets.
+ Ensures that an ignored 'os.Mkdir' error is not thrown. Could have
used os.MkdirAll but then want to track the lack of parents locally.
=> exports: fix regression for exports

cmd/drive/main.go, config/config.go
* `Context` now maintains a DB handle that is kept alive
=> Remove per-operation `Open()`/`Close()` calls to BoltDB

cmd/drive/main.go, src/changes.go, src/commands.go, src/help.go, src/misc.go, src/push.go, src/remote.go, src/types.go
This PR addresses issues #315 and #77. It also fixes the bugs and complexity in PR https://github.com/odeke-em/drive/pull/210.
* Introduces a flag `--v` for `verbosity` during push to see step by step information.
* Introduces $GOMAXPROCS to be the number of max parallel uploads. Default is 4.
To test it out:
```shell
$ go get -u github.com/odeke-em/drive
$ cd $GOPATH/src/github.com/odeke-em/drive
$ git checkout easier-parallel-uploads-caching && git fetch --all
$ go get ./drive-gen && drive-gen
$ drive push -v [paths...]
```
=> Easier parallel uploads caching

src/misc.go, src/remote.go
This PR addresses issue #320. It adds exponential backoff for pushes in cases where say the userRateLimit is exceeded, or Google Drive encounters an internal server error. The upload should be retried after pausing for an exponentially increasing amount of time until a maximum number of tries.
=> exponential-backoff for push implemented

src/sort.go
The previous use of a collator was causing a lot of out memory
problems for folks on low powered devices. The old collator
actually was using an undefined language locale so seems
unnecessary.
This PR addresses issues #330 #329 https://github.com/odeke-em/drive/issues/273 https://github.com/odeke-em/drive/issues/323.
=> sort: perform plain string comparison

README.md, cmd/drive/main.go, src/pull.go, src/push.go
This PR addresses issue #332 and in particular, details are:
+ Cleaned up the legacy goroutine rationer for pulls.
+ Added a verbose option for showing the current operation.
=> pull: cleaned up goroutine rationer + verbose opt

cmd/drive/main.go, config/config.go
=> db: no need to entirely lock DB unless needed

README.md, cmd/drive/main.go, src/help.go, src/publish.go, src/types.go, src/url.go
This PR addresses issue #348 and allows for users to get the urls of files either by relative path or by id
```shell
$ drive url Photos/2015/07/Releases intros/flux
$ drive url --id  0Bz5qQkvRAeVEV0JtZl4zVUZFWWx  1Pwu8lzYc9RTPTEpwYjhRMnlSbDQ 0Cz5qUrvDBeX4RUFFbFZ5UXhKZm8
```
=> url command implemented

README.md, cmd/drive/main.go, src/help.go, src/open.go
This PR addresses issue #351.
It provides the functionality for drive to open files that exist at least remotely, in the default file browser or the designated web browser, either by relative path or by id.
```shell
$ drive open --file-browser=false --web-browser f1/f2/f3 jamaican.mp4
$ drive open --file-browser --id 0Bz8qQkpZAeV9T1PObvs2Y3BMQEj 0Y9jtQkpXAeV9M1PObvs4Y3BNRFk
```
=> open command added

src/remote.go, src/types.go
This PR addresses issue #354.
Use the standard Google Drive entry point url instead of the
hostURL which is useful for published files but not for private ones.
=> serve-url: use open entry point instead of hostURL

src/misc.go
This is because Google Drive fails to convert text/csv types
to Spreadsheets, however with the Spreadsheet coercion it alludes
them to Spreadsheets but on final open it will fully convert it to a
Google Sheet. See the tricky thing though is that trying to force
csv/tsv directly to Google Sheets fails since Google Docs catches this
and then reverts them to text documents.
=> coerce csv,tsv to officedocs

src/misc.go
This PR fixes issue #368. I figured out the mimeType by uploading a pptx file using the WebUI and then
```shell
$ drive stat test.pptx
....
MimeType                  application/vnd.ms-powerpoint 
....
````
=> fixed mimeType for pptx?

src/remote.go
Seconds should be padded to be two characters for consistency.
=> Corrected padding for seconds

src/misc.go, src/move.go
This PR addresses issue #379 by ensuring that errors get well composed if any and then returned at the end.
Given 
```shell
$ drive push proof.go no-chill.mp4 proofs && echo "Done" || echo -e "Failed \a"
move: /proof.go: src('/proof.go') remote path doesn't exist
move: /no-chill.mp4: src('/no-chill.mp4') remote path doesn't exist
"Done"
```
```shell
$ drive push proof.go no-chill.mp4 proofs && echo "Done" || echo -e "Failed \a"
move: /proof.go: src('/proof.go') remote path doesn't exist
move: /no-chill.mp4: src('/no-chill.mp4') remote path doesn't exist
Failed
```
=> move: compose multiple errors into one

README.md
Minor change to correct name of `-ignore-name-clashes` argument.
=> Readme: Correct ignore-name-clashes arg

src/push.go
This PR is a work in progress to fix issue #384 by compensating for remote modifications e.g deletions as opposed to only pushes. It just uncomments and apply a TODO that I had in previously.
=> quota: uncomment + apply quota mod compensations

src/push.go
This PR addresses issue #386 
```shell
$ drive push --no-prompt resty_demo.mov && echo done
Resolving...
projected size: (1346167232) 1.25GB
Proceed with the changes? [Y/n]:
```
```
$ drive push --no-prompt resty_demmov && echo done || echo "aborted"
Resolving...
quota: noPrompt is set yet for quota projected size: (1346167232) 1.25GB
aborted
```
=> quota: respect no-prompt on exceeded err

src/push.go, src/types.go
This PR fixes issue #392.
What was happening was the both source and destination were being derived from the remote file and no actual modTime update was being done before push.
=> push-piped: update ModTime on push

src/misc.go
This PR addresses issues https://github.com/odeke-em/drive/issues/358, https://github.com/odeke-em/drive/issues/345, https://github.com/odeke-em/drive/issues/371 and others.
In relation to a large set of unknown errors, moreover looking at
https://github.com/google/google-api-go-client/issues/93
where we are type casting to a googleapi.Error yet errors could be
dial/net related errors, it is safer to make the largely unknown errors
retryable.
This actually helps a lot say when downloading files and the connection
is cut out maybe due to WiFi trips or going underground.
=> unknown errors now retryable by default

src/about.go, src/remote.go, src/stat.go, src/types.go
See https://golang.org/s/go14customimport for an explanation.
Fixes the below warning:
package github.com/google/google-api-go-client/googleapi: code in
directory
$GOROOT/src/github.com/google/google-api-go-client/googleapi
expects import "google.golang.org/api/googleapi"
=> Update google api dependencies to use canonical path

src/push.go
This PR addresses issue #415 
```shell
$ cd testDrive
$ ls -l ~/Desktop/continuations
total 12
-rwxrwxr-x 1 emmanuel emmanuel 7579 Jan 13  2015 gen
-rw-rw-r-- 1 emmanuel emmanuel  709 Dec 30  2014 gen.c
$ drive push -m ~/Desktop/continuations .
Resolving...
+ /continuations
+ /continuations/gen
+ /continuations/gen.c
Addition count 3 src: 8.09KB
Proceed with the changes? [Y/n]:
```
=> push: pass in depth for mounted push

README.md, cmd/drive/main.go, src/commands.go, src/help.go, src/pull.go, src/push.go, src/remote.go
This pull request is a draft. I would like to know if you are interested in implementing such a mechanism to automatically rename files on drive to prevent name clashes. Right now, if some clashes occur, user is advised to go to drive and resolve name conflicts before doing pull. While this is probably the safest option, I personally wouldn't bother when there is more than a few clashes. This functionality is racy and may not be safe but it does automate the task and I think may still be useful if users are properly warned. What do you think?
I don't know neither code base nor Go so I'm aware that the code itself requires polishing.
=> fix-clashes

README.md, cmd/drive/main.go, src/edit.go, src/help.go, src/misc.go, src/remote.go, src/url.go
This PR addresses issue https://github.com/odeke-em/drive/issues/414
You can now run
```shell
$ drive edit-description --description "This summer's photos right here" photos/Ibiza 2015/07/25
$ drive edit-desc --description "This is a description" f1/f2.txt openSrc
$ cat descriptions | drive edit-desc --piped fl/ newestFolders/f1/f2
```
=> edit-file functionality added

src/pull.go
This PR addresses issue https://github.com/odeke-em/drive/issues/389
For pull-matches, the relative path was erraneiously
added as
"/" + match.Name
This meant that any item that resulted from pull-matches
was made relative to the root instead of the current working directory
=> pull-matches: fixed up relative path

src/changes.go, src/commands.go, src/pull.go, src/push.go
This PR addresses issue https://github.com/odeke-em/drive/issues/300
Previously no-prompt dictated what could be printed during an operation.
However this behaviour was wrong since setting --verbose during a
push/pull yet with --no-prompt would not print out  the manifest.
Also users requested for previews even if no-prompt was set and this is
the correct behaviour.
=> preview: show previews independent of no-prompt

src/remote.go, src/touch.go
This PR addresses issue #442 by fixing up a bug in which while multiplexing over
the channels and looking for channels that had been drained,
legacy select code still had a forced `nil` emission at a deferred
statement. However, once a channel has been drained, any attempt to
read from it will also return `nil`. Coupling this knowledge with
a recursive traversal of children, `nil` was being added prematurely.
It also refactors the code used by the plain Touch and TouchByMatch
.
```shell
$ drive touch --recursive
/ENGINEERING/Fall2015/BLAW_301: 2015-10-26 02:06:21 +0000 UTC
/ENGINEERING/Fall2015/BLAW_301/ch01.ppt: 2015-10-26 02:06:22 +0000 UTC
$ drive list
/ENGINEERING/Fall2015/BLAW_301/ch01.ppt 
/ENGINEERING/Fall2015/BLAW_301/ch02.ppt 
/ENGINEERING/Fall2015/BLAW_301/ch03.ppt …
```
=> touch: fixed up premature force exit on nil elem

src/changes.go
This PR fixes issue #444 
Fixes a regression bug in which hidden wasn't being passed into
an fsListingArg item before a local listing.
=> pull/push: pass in Hidden

cmd/drive/main.go, src/help.go
This PR links a user to the discussion on why we don't enable `--no-prompt` as the contents of discussion #448.
```shell
$ drive delete --no-prompt fox
flag provided but not defined: -no-prompt
Usage of delete:
-h	
-hidden
allows trashing hidden paths
-id
delete by id instead of path
-matches
search by prefix and delete
-quiet
if set, do not log anything but errors
```
```shell
$ drive delete --no-prompt fox
"no-prompt" is set yet performing a permanent deletion. Please see issue https://github.com/odeke-em/drive/issues/448
```
=> delete: link user to no-prompt discussion

cmd/drive/main.go
This PR addresses #451 
Previously the contextAbsPath was erraneously gotten by a
filepath.Abs(path) operation. However this is wrong and only
works when running from the root folder. The correct way is
to filepath.Join(root, path)
=> mounted-push: contextAbsPath joined from root

cmd/drive/main.go, src/qr-share.go
This PR addresses issue https://github.com/odeke-em/drive/issues/453
=> qr-share: use default credentials plus global app

src/pull.go, src/types.go
Ensure that ModTimes for dirs and folders
aren't ignored and are always matched up.
This PR fixes issue #463
=> consider ModTime for dirs/folders

src/changes.go
This PR addresses issue #462.
The bug was that the traversalDepth was being derived from the remote depth which was predecrement before doing a local listing, this meant that local listing always got a depth - 1 and hence manifested in the bug where the next level's changes were being reported as non existant locally
=> ensure equal local + remote traversal depths

src/misc.go
An immutable file mutation error is non retryable
This PR avoids the scenario in issue #472 in which a mutation was being made on the root '/' yet this file cannot be mutated.
=> retry: false if immutable file mutation attempted

README.md, cmd/drive/main.go, src/help.go, src/pull.go, src/remote.go, src/types.go
This PR finishes up and introduces the ability to pull all starred files finishing up https://github.com/odeke-em/drive/issues/431
Retraces full path given the fileId hences aids
in pull all the starred files
```shell
$ drive pull --all --starred
```
=> pull-all-starred

src/pull.go, src/types.go
This PR addresses https://github.com/odeke-em/drive/issues/477.
directories get spurious modTime changes from ordinary mutating
shell operations on their children e.g rm, touch, mv etc.
Allowing for dirs to have accurate modTimes risks creating bad
user experience for which actually the user shouldn't have to worry
about and the previous change introducing this behaviour was just
being strict.
=> ignore dir modTimes

README.md, cmd/drive/main.go, src/remote.go, src/touch.go
=> Touch traversal depth

README.md, cmd/drive/main.go, src/help.go, src/remote.go, src/share.go
This PR addresses issue #484 and allows users to specify emails of users they'd like to unshare to as well as multiple roles. This also happens for 'share'.
Allows unsharing by `--emails`, multiple roles, multiple accountTypes
and makes it easier to revoke or share access across to multiple
people.
=> multi-role-account-sharing

src/misc.go
Coercing csv, tsv to officedocument (#357) doesn't work around #232 ("Push flag "-convert" has no effect"). Therefore there is no need for this hack.
=> Fix CSV and TSV mime types

src/rc.go
This PR fixes issue #488 
CSV values get parsed in the cmd/drive/main.go command after
they've already been parsed from the RC. The remedy here
is to pass back such values as they are to be handled appropriately.
=> rc: fix premature string array conversion

cmd/drive/main.go, src/diff.go, src/help.go, src/rc.go
This PR addresses #494 and provides a unified diff option ie
```shell
$ drive diff -u [paths...]
```
by default `-u` is set to true therefore to turn it off
```shell
$ drive diff -u false [paths...]
$ drive diff -u=false [paths...]
```
```shell
$ drive diff ls.txt 
File: /diff-test/ls.txt
* local:          2015-11-26T17:32:49.000Z                
* remote:         2015-11-26T17:32:09.000Z                
ls.txt
****
--- /Users/emmanuelodeke/emm.odeke@gmail.com/diff-test/ls.txt	2015-11-26 10:32:49.000000000 -0700
+++ .xtmp5577006791947779410.tmp666634729	2015-11-26 10:33:03.000000000 -0700
@@ -1,6 +1,15 @@
-LICENSE
-README.md
-cache.go
-cache_test.go
-exports.go
-swift
+02 Downtown (feat. Kidd Kidd).m4a
+About_A_Girl.mp3
+drop.avi
+sample.3gp
+sample.m4a
+sample.midi
+sample.wav …
```
=> diff: unified diff option added

src/misc.go
This PR fixes issue #500 and deterministically distinguishes between docs and docx files.
=> fixed docs vs docx regex clash

src/share.go
Fixes #503
Allows types like domain, roles like reader etc to
be revoked without having to supply emails. In fact
domain access revokation doesn't have a specific email
so also needs to be handled.
=> unshare: can now revoke access for non-email types

README.md, cmd/drive/main.go, src/commands.go, src/diff.go, src/help.go, src/misc.go, src/rc.go
Fixes #506
Allows users to switch decide if local
is the base otherwise use remote.
```shell
$ drive diff --base-local=false ls.txt 
File: /diff-test/ls.txt
* local:          2015-11-26T17:32:49.000Z                
* remote:         2015-11-26T17:32:09.000Z                
ls.txt
****
--- .xtmp5577006791947779410.tmp537523880	2015-11-29 20:11:18.000000000 -0700
+++ /Users/emmanuelodeke/emm.odeke@gmail.com/diff-test/ls.txt	2015-11-26 10:32:49.000000000 -0700
@@ -1,15 +1,6 @@
-02 Downtown (feat. Kidd Kidd).m4a
-About_A_Girl.mp3
-drop.avi
-sample.3gp
-sample.m4a
-sample.midi
-sample.wav
-sample_3GPP2.3g2
-sample_iPod.m4v
-sample_iTunes.mov
-sample_mpeg2.m2v
-sample_mpeg4.mp4
-violin07.aif
-violin12.aif
-zips
+LICENSE
+README.md
+cache.go
+cache_test.go
+exports.go
+swift
```
```shell
$ …
```
=> diff: allow base switching between local or remote

src/pull.go
Fixes #496.
Now allows for docs to be exported when modified since before
there was a clause that prevented files from being downloaded
if their checksums varied, of which exportable docs have no
raw content hence their checksums will always be the same
yet this is registered as only a ModTime change.
=> pull: export exportables on mod without checksum

README.md, cmd/drive/main.go, src/pull.go, src/remote.go
Fixes #515.
This PR allows for a user to distinguish between
trashed and untrashed starred files.
=> pull/starred: separate trashed and untrashed.

src/commands.go
Fixes #524.
For commands such as `init`, the opts are nil so use
the vanilla logger for such cases and don't panic.
=> new: define a custom logger if opts==nil

src/changes.go, src/diff.go, src/misc.go, src/pull.go, src/push.go, src/remote.go
This PR gives the ability for multiple matches to be returned as opposed to the old style that assumed that only the head would be needed. It is essential to return and explore/traverse all potential matches. This helps fix issues like https://github.com/odeke-em/drive/issues/317 and it is better + cleaner version of PR https://github.com/odeke-em/drive/pull/356.
This PR also ensures that all clashes are reported too during a diff, pull and push.
=> find*Multi version to find all clashes and matches

README.md, cmd/drive/main.go, src/clashes.go, src/help.go, src/pull.go, src/remote.go
Added ability to:
* List clashes.
* Fix clashes.
```shell
$ drive clashes dup-tests/a/b/c/d/e
These paths clash
X /dup-tests/a/b/c/d/e/f 0By5qQkvRAeV2Wk9FaEN4ZzNock0
X /dup-tests/a/b/c/d/e/f/g 0By5qQkvRAeV2amN5aFgzc1htVXM
X /dup-tests/a/b/c/d/e/f/g 0By5qQkvRAeV2N21ETkVCTHpkcEE
X /dup-tests/a/b/c/d/e/f/g/h/i 0By5qQkvRAeV2TWdVb29DRlVXR1k
X /dup-tests/a/b/c/d/e/f/g/h/i 0By5qQkvRAeV2Vk9lY3Y2SjFDYlE
X /dup-tests/a/b/c/d/e/f 0By5qQkvRAeV2TzE3LXNWVFNoaHM
X /dup-tests/a/b/c/d/e/f 0By5qQkvRAeV2NmEwUmFQOEZ0dE0
X /dup-tests/a/b/c/d/e/f 0By5qQkvRAeV2bm5ZRVpELXRHTWM
```
```shell
$ drive clashes --fix [paths...]
$ drive clashes  --fix dup-tests/a/b/c/d/e
Some clashes found, we can fix them by following renames:
/dup-tests/a/b/c/d/e/f 0By5qQkvRAeV2TzE3LXNWVFNoaHM -> f_0
/dup-tests/a/b/c/d/e/f …
```
=> added a clashes command

src/changes.go, src/clashes.go, src/id.go, src/pull.go, src/push.go, src/remote.go
Fixes #536.
Updates #528.
It is an offset of PR #528, caused by the new pattern remote.FindByPathM -- multiple which returns a channel. Originally a call
```go
files, err := req.Do()
if err != nil {
if err.Error() == ErrGoogleApiInvalidQueryHardCoded.Error() { // Send the user back the query information
err = fmt.Errorf("err: %v query: `%s`", err, expr)
}
return nil, err
}
if files == nil || len(files.Items) < 1 {
return nil, ErrPathNotExists
}
first := files.Items[0]
if len(p) == 1 {
return NewRemoteFile(first), nil
}
return r.findByPathRecvRaw(first.Id, p[1:], trashed)
```
The original pattern guaranteed the reporting of unmatched files
and yet now
```go
for rem := range remotesChan {
....
}
```
// Will never be run if the file didn't exist upstream.
yet at no point was a lack of the …
=> propate no-match found `nil` file after find* channel based queries

README.md, src/changes.go, src/commands.go, src/misc.go, src/misc_test.go
Fixes #535.
As of time:"1451307614.785091", Go apparently doesn't have a
"negative lookahead" mechanism ie `ignore all but`. This commit
adds an `exclude but for` clause that mitigates this shortcoming.
=> ignorer: added include + exclude handling

README.md, cmd/drive/main.go, src/help.go, src/issue.go
This requires a web browser for the issues tracker to be opened.
For example:
```shell
$ cat bugReport | drive report-issue --title "Crash on pushing"
$ drive report-issue --title "Crash on pushing" --body "Similar to #5 but here always crashes only after a timeout"
```
=> issue-filing can now be started from the terminal

src/misc.go
Fixes #551.
Ensures that the proper mimeType is used for pptx files
since before the format was that of `open ms-powerpoint`
yet it is `openxmlformats-officedocument.presentationml.presentation`.
=> pptx mimeType corrected

src/list.go
Fixes #557.
Strips unnecessary space from the end of the path.
=> src/list: strip trailing space from list

README.md, cmd/drive/main.go, src/diff.go, src/help.go
Fixes #585.
Adds a flag `--skip-content-check` to diff.
This prevents the need for diffing the content
and just shows only until the time changes.
```shell
$ drive diff
File: /test-585/influx
* local:          2016-02-12T08:12:09.000Z                
* remote:         2016-02-12T08:10:18.000Z                
influx
****
--- /Users/emmanuelodeke/odeke@ualberta.ca/test-585/influx	2016-02-12 00:12:09.000000000 -0800
+++ .xtmp5577006791947779410.tmp522394888	2016-02-12 00:12:54.000000000 -0800
@@ -1,7 +1,2 @@
admin
influx
-admin
-influx
-off
-off1
-today
****
/test-585/off1 only on local
/test-585/today only on local
/test-585/off only on local
```
```shell
drive diff --skip-content-check
File: /test-585/influx
* local:          2016-02-12T08:12:09.000Z                
* remote: …
```
=> diff: add skip-content-check flag

src/help.go, src/misc.go
Fixes #583.
Updates #551.
Fixes an ambiguity with the regexes for `ppt` and `pptx`.
The problem was that `ppt` and `pptx` are unterminated regex-wise
so `pptx` would get matched as `ppt` and then undeterministically
also matched as `pptx`.
This mean that `pptx` would give two different mimeTypes ie
```json
"ppt":    "application/vnd.ms-powerpoint",
"pptx":   "application/vnd.openxmlformats-officedocument.presentationml.presentation"
```
The fix is to terminate them as `ppt$` and `pptx$` to properly
differentiate between the two.
=> pull/export: fixed ppt vs pptx regex ambiguity

README.md
README.md says ```pull``` when it means ```push```.
=> Fixed a copy/paste error

src/pull.go
The messages were prefixed `push:`, which is probably from a copy/paste.
=> Fix error message prefix in pull.

src/edit.go
This patch improves error handling in EditDescription.
drive edit-desc returned 0 in some cases, like "remote path doesn't exist".
Fix the following issue where rc=0:
```
$ drive edit-desc gdrive/regal/e6/2d/bb/0x200010896:0x1f237:0x0
Using an empty description will clear out the previous one
Proceed with the changes? [Y/n]:y
/gdrive/regal/e6/2d/bb/0x200010896:0x1f237:0x0: remote path doesn't exist
$ echo $?
0
```
With this patch, rc=1 instead.
=> edit-desc: fix error handling to get proper return code

cmd/drive/main.go, src/changes.go, src/clashes.go, src/copy.go, src/diff.go, src/errors.go, src/errors_test.go, src/id.go, src/list.go, src/misc.go, src/move.go, src/pull.go, src/push.go, src/remote.go, src/share.go, src/trash.go
Fixes #479.
Now most errors returned from drive have a status/return
code that will be passed to the external environment on failure.
- Before
```shell
$ drive pull nonExistant
Resolving...
–
'/ysms' aka '/Users/emmanuelodeke/emm.odeke/nonExistant' doesn't
exist locally nor remotely
$ echo $?
1
$ mkfifo pxm
$ drive push pxm
Resolving...
–
/pxm (/Users/emmanuelodeke/emm.odeke/pxm) is a named pipe, yet
not reading from it
$ echo $?
1
```
- After
```shell
$ drive pull nonExistant
$ echo $?
8
$ mkfifo pxm
$ drive push pxm
Resolving...
–
/pxm (/Users/emmanuelodeke/emm.odeke/pxm) is a named pipe, yet
not reading from it
$ echo $?
22
```
=> implemented errors with status/return codes.

src/remote.go
Fixes #609.
Updates #608.
Fixes up a mistaken global search and replace for
GoogleAPIs introduced in PR #608.
=> DriveScope: s/GoogleAPIs/googleapis/g

README.md, cmd/drive/main.go, src/changes.go, src/commands.go, src/help.go, src/misc.go, src/push.go, src/remote.go
Added the ability to push directly to a final destination
without copying content, remotely/locally nor moving, using
option `--destination`.
- Sample usage:
To push the content of `music/Travi$+Future`, `integrals/complex/compilations` directly to `a1/b2/c3`:
```shell
$ drive push --destination a1/b2/c3 music/Travi$+Future integrals/complex/compilations
```
where the sources exist on disk.
Fixes #612.
=> push: added --destination arbitrary within root pushes

src/changes.go, src/misc.go, src/push.go
Keep track of the local vs remote base since we are no longer
only pushing from a single location on disk/local.
Also ensure that all paths in a push/changelist-resolve are
separator prefixed since searching for remote files always
starts with '/' as was the old style. Passing in say 'lib/f1'
is invalid since the search starts from '/' so must be '/lib/f1'.
Fixes #618
Updates #616
Updates #612
=> push/changes: keep track of local vs remote base

src/misc.go
According to https://www.openoffice.org/framework/documentation/mimetypes/mimetypes.html the mime-type for ODS should be application/vnd.oasis.opendocument.spreadsheet
Fixes #620
=> Fix mime-type for ODS

src/push.go
Hi @odeke-em This is a small change I made after noticing a few rare cases of push -piped failing but return code was 0. I tested this fix during a few hours without seeing the problem anymore.
=> push -piped: return error in case of remoteMkdirAll failure

README.md, cmd/drive/main.go, src/commands.go, src/help.go, src/move.go
By default, rename will also rename the equivalent local path.
This CL also allows toggling whether to rename local or remote.
However, it resolves the file to change based off the remote path
- To turn off local renaming
```shell
$ drive rename --local=false a/b/c/d pam
```
- To turn off remote renaming
```shell
$ drive rename --remote=false bcd tkf
```
It also warns the user of an error if they turn off all modes.
```shell
$ drive rename --local=false --remote=false 5 6
no rename mode set, set either `local` or `remote` mode
$ echo $?
8
```
Fixes #459.
=> rename: add local + remote modes

README.md
Because of dependency requirements calling for at least go1.5, we need to
bump the requirement in the README.
```shell
$ go get -u github.com/odeke-em/drive/cmd/drive
golang.org/x/net/context/ctxhttp
../gopath/src/golang.org/x/net/context/ctxhttp/ctxhttp.go:35: req.Cancel
undefined (type *http.Request has no field or method Cancel)
```
Fixes #630.
Updates #627.
=> README: min go version bumped to go1.5

src/share.go
Allow sharing of file with `anyone with link` without
having to publish it to the internet. Publishing is different
because after a file is published, it is indexed
(See https://github.com/odeke-em/drive/issues/568#issuecomment-175262035).
We don't want the file to be indexed, but just accessible by anyone with
a link to it.
```shell
$ drive share --type user,anyone,anyone,user --role reader,anyone --emails "emm.odeke@gmail.com" outf.gif
Provide access for accountType(s)
user
anyone
For roles(s)
reader
Addressees:
+ emm.odeke@gmail.com
+ Anyone with the link
File(s) to share:
+ outf.gif
Proceed with the changes? [Y/n]:y
successful share for outf.gif with email "emm.odeke@gmail.com", role "reader" accountType "user"
successful share for outf.gif with email "", role "reader" accountType …
```
=> share: anyone with link, not publicly published

README.md, cmd/drive/main.go, src/commands.go, src/help.go, src/pull.go, src/push.go, src/remote.go
Data should only be unencrypted on the user's local disk but
should always be encrypted remotely on Google Drive, if the
password was provided.
- When a password is provided, encrypt the data before it is received
by Google Drive. Encrypt for upload:
```shell
$ drive push --encryption-password foolsGold issueFilingDrive.mp4
```
- When a password is provided, decrypt the data before writing
it to disk:
```shell
$ drive pull --piped issueFilingDrive.mp4 --decryption-password
foolsGold > txt.v
```
=> E2E: encrypt on upload, decrypt on download

src/changes.go, src/commands.go, src/dcrypto/dcrypto.go, src/dcrypto/v1/v1.go
This change allows the local and remote file sizes to match so
that push/pull can skip files. It does have the side effect that
if the user wanted to change the password they'd have to force.
=> E2E: Adjust the remote size when using encryption.

src/about.go
Bumping to v0.3.7 special release so that E2E Encryption
feature is the top release for everyone to use.
=> version: bump to v0.3.7 for special release

.gitignore, Makefile, README.md
Added a Makefile for cross compilation during releases and to
democratize compilation for users themselves.
Updates #662.
=> Makefile for cross compilation added

README.md, cmd/drive/main.go, src/changes.go, src/list.go, src/misc.go
push and pull now allow for selection of types
e.g only files, only directories using flags
`--files` or `--directories`.
- Exhibit A: No type sifting/selection -- ordinary pull
```shell
drive pull a1
Resolving...
- /test/a1
- /test/a1/b2
- /test/a1/b2/c3
- /test/a1/b2/c3/d4
- /test/a1/b2/c3/d4/e5
- /test/a1/b2/c3/test.txt
Deletion count 6
Proceed with the changes? [Y/n]:
```
- Exhibit B: only files
```shell
$ drive pull --files a1
Resolving...
- /test/a1/b2/c3/test.txt
Deletion count 1
Proceed with the changes? [Y/n]:
```
- Exhibit C: only directories
```shell
$ drive pull --directories a1
Resolving...
- /test/a1
- /test/a1/b2
- /test/a1/b2/c3
- /test/a1/b2/c3/d4
- /test/a1/b2/c3/d4/e5
Deletion count 5
Proceed with the changes? [Y/n]:
```
- Exhibit D: illogical state, both files and …
=> push/pull: files and directories type selection

README.md, cmd/drive/main.go, src/help.go, src/remote.go, src/share.go
Enables sharing to anyone with the link but the file won't be
publicly indexed as is usually with files that are published publicly.
```shell
$ drive share --with-link ComedyPunchlineDrumSound.mp3
```
Fixes https://github.com/odeke-em/drive/issues/568.
Follows suggestions in
https://github.com/odeke-em/drive/issues/650#issuecomment-222927083.
=> share: with-link to avoid public file indexing

src/rc.go
In PR https://github.com/odeke-em/drive/pull/676,
I touched up the signature and content for function
`JSONStringifySiftedCLITags` to not use named return values.
However, I changed the error check from `ResourceMappings`
to just be `err`. The first check ensures that either a file
exists or doesn't exist. Reusing that variable at the end of
the function meant that any previous error checks for rc paths
that didn't exist were being returned and this would send
back os.ErrNotExist yet the intention of the function
is to digest this error as a check and not as a return value.
Fixes https://github.com/odeke-em/drive/issues/677.
=> rc: fix err variable reuse

src/changes.go
Updates #681.
Fixes a crash introduced by PR 673, in which in cases that we were doing
`push -m`, we'd have nil filters, and dereferenced one.
=> src/changes: do not dereference nil filter

src/rc.go
Resource configuration mappings now recognize keys
+ encryption-key
+ decryption-key
```shell
$ cat .driverc
hidden=true
encryption-password=bonjour
decryption-password=bonjour
$ drive push test.mp4 # Should be encrypted at rest
$ drive pull --piped test.mp4 > outf && diff outf test.mp4 # Should be decrypted properly
```
Fixes https://github.com/odeke-em/drive/issues/683.
=> rc: register encryption+decryption key variables

README.md, cmd/drive/main.go, src/commands.go, src/help.go, src/pull.go
Fixes #660.
Allow exporting to same directory and level, instead of:
a) Always dumping exports per exportable file in a sub-directory
called `<filename>_exports`.
This CL allows for users to request that their exports be put in the
same directory with pull flag `--same-exports-dir`.
If `--same-exports-dir` is set, it will place all exports in the same
directory and level.
* Exhibit A:
```shell
drive pull --explicitly-export --exports-dir ~/Desktop/exp --export
pdf,txt,odt --same-exports-dir
Resolving...
+ /test-exports/few.docs
+ /test-exports/few
+ /test-exports/influx
Addition count 3
Proceed with the changes? [Y/n]:y
Exported '/Users/emmanuelodeke/emm.odeke@gmail.com/test-exports/influx' to '/Users/emmanuelodeke/Desktop/exp/influx.pdf'
Exported …
```
=> pull/export: allow exporting to same directory+level

README.md, cmd/drive/main.go, src/commands.go, src/help.go, src/pull.go
Fixes #697.
Users can now turn off *.desktop file creation by using flag
`--desktop-links` e.g
```shell
$ drive pull --desktop-links=false
```
=> pull: allow disabling of *.desktop file creation

.gitignore, src/list.go, src/remote.go
=> list: fix --trashed to return all items in the current working directory

cmd/drive/main.go, src/push.go
Fixes https://github.com/odeke-em/drive/issues/641.
+ Refactored push mounted, removing/generalizing code for
mounts to use same as ordinary pushes.
+ Ensure that in cmd/drive/main.go, after a mounted push
we return appropriately otherwise we were erraneously falling
to start an ordinary push which would trigger a bug with
a bad context. This is akin to the common C-style switch bug in which
one forgets to break/return.
+ Fixed up a bug with mounted push where if the user
specified a single mounted path, the current working
directory wouldn't be added to the arguments that needed
to be processed. It was an error comparison mismatch.
=> push/mounted: fix unload of paths in root + no return catch

src/help.go, src/list.go
Fixes https://github.com/odeke-em/drive/issues/714.
Sort attributes passed in from the commandline are csv values e.g
```shell
$ drive list -sort name_r,modtime
```
The bug previously was that these values were actually never getting
split by comma values, in cmd/drive/main. This CL ensures that we
do the necessary splitting and whitespace trimming before we
make the sorters.
It also updates the CLI doc on sort:
* Before
```shell
$ drive list -sort
-sort string
sort items in the order
* md5.
* name.
* size.
* type.
* version
```
* After
```shell
$ drive list -sort
-sort string
sort items by a combination of attributes
* modtime.
* md5.
* name.
* size.
* type.
* version
```
=> sort: fixed sorters to be split by comma

src/remote.go
Drive Web Hosting is being discontinued
(https://support.google.com/drive/answer/2881970?hl=en)
=> Use API download instead of Drive Web Hosting

src/remote.go
Updates https://github.com/odeke-em/drive/pull/735.
Ensure that we can still pull exports after a body
fetch for exports was accidentally taken out.
=> pull: ensure we can still pull exports

src/pull.go
Fixes https://github.com/odeke-em/drive/issues/734.
Capture errors after parallelized pulls.
Also avoid shadowing errors on result waiting.
The changed code was legacy of an oversight after the old days
in which we didn't send back exit codes to the outside world.
After exit codes were added to drive, the pull code was never touched.
Even still though, we had logging for errors and users could see their
errors.
Exhibits:
* Unsuccessful pull
```shell
drive pull --export pdf,rtf t1; echo $?
Resolving...
$ drive pull --export pdf,rtf t1; echo $?
Resolving...
M /test-docs/t1
Modification count 1
yroceed with the changes? [Y/n]: –
/test-docs/t1 err: download: failed for url "". StatusCode: 400
download: failed for url "". StatusCode: 400
255
```
* Successful pull
```shell
$ drive pull --export …
```
=> pull: relay along errors encountered

src/changes.go, src/clashes.go, src/copy.go, src/id.go, src/list.go, src/pull.go, src/remote.go, src/stat.go, src/touch.go, src/trash.go
Fixes https://github.com/odeke-em/drive/issues/480.
Fixes https://github.com/odeke-em/drive/issues/668.
Fixes https://github.com/odeke-em/drive/issues/728.
Fixes https://github.com/odeke-em/drive/issues/738.
Ensure that we propagate any remote file resolution errors
during pagination.
Previously pagination was done in a goroutine that just sent
back a channel of files. However, this design meant that
if errors were encountered during the resolution, the channel
would close after just
```go
if err != nil {
fmt.Println(err)
break
}
```
and then close the channel.
Meanwhile the problem then bubbled up to the resolver
that determined which files exist and which don't
thereby triggering deletion operations claiming the remote
files didn't exist say when we Google Drive encountered a 500 or a …
=> propagate and handle remote file resolution errors

README.md
Fixes https://github.com/odeke-em/drive/issues/690.
Document that modTime on its own is an operation that doesn't
necessarily warrant resyncing the contents of a file.
=> README: document lone modTime change behavior in checksum verification

src/about.go
Fixes https://github.com/odeke-em/drive/issues/743.
Version bumped up to v0.3.8, new release.
=> version bump to v0.3.8!

src/about.go
Small point release to make it easy for folks
to get around https://github.com/odeke-em/drive/issues/749.
=> small point release to v0.3.8.1!

src/share.go
Ensures that we can still share files by emails
Fixes https://github.com/odeke-em/drive/issues/762.
=> share: fix regression in which emails were no longer being set

README.md
Bourne shell interpolates "$JiME5Umf" as an unset variable and the
result is passing an empty string to --decryption-password. Using single
quotes avoids this problem.
=> quote $ to avoid variable interpolation

src/list.go, src/remote.go
Fixes https://github.com/odeke-em/drive/issues/724.
Fix print pagination prompts to only be done after
retrieving all the children within the same level
otherwise we get spurious prompts which is incorrect
behavior that doesn't match what pagination
is for.
Previously due to spurious prompts after every
single pagination within the same level, we'd
get prompts such as:
```shell
---More---
---More---
---More---
---More---
```
even before a single item was printed.
This change fixes that behavior.
The old behavior meant to alleviate problems with rate limits
but actually caused more problems and embarrasement for
printing than the remedy.
Anyways, we have a throttle of 1/10th of a second in place
between next pages.
=> list: pagination prompts only after each depth level of children

src/changes.go, src/types.go
Fixes https://github.com/odeke-em/drive/issues/769.
Handle the case where the local and remote objects
of a directly addressed path have different dirTypes ie
one is a regular file, the other is a directory/folder.
It returns an IllogicalStateError whose status can
be checked in the shell.
Fixes a TODO that has been waiting to be fixed.
Ensures that the case is caught e.g
* Exhibit:
```shell
$ drive new --mime-key docs share_test
$ mkdir -p share_test
$ drive pull share_test; echo $?
Resolving...
/share_test: local is a directory while remote is a file
8
```
=> handle differing dirTypes on direct addressing

src/share.go
Fixes https://github.com/odeke-em/drive/issues/747.
By default use accountType User, as is done with share,
so that users can easily do things like
```shell
$ drive unshare -emails somebody@gmail.com -id some_id
```
instead of getting back a cryptic error
```shell
no matches found!
```
and the common assumptions will work without them
having to know the entire setup of share and unshare.
I too found this confusing and had to step back a little
to figure out that previously the accountTypes were
never set hence the loop that runs through each file
never runs.
This change also ensures that if errors were encountered entirely
errors, without any successful shares/unshares, we won't give back
the previously cryptic and not useful error of
```shell
no matches found!
```
=> unshare: use by default accountType User

README.md
I opt'd to use a single hyphen for options. And made a small note in regards to the ability to swap. I think a single hyphen fits because of the internal help examples use a single hyphen.
=> uniform hyphen usage addresses #772

src/changes.go, src/pull.go, src/push.go
Fixes https://github.com/odeke-em/drive/issues/177.
For some operations such as OpDeletion counter.src == 0
yet counter.dest > 0.
Translation is if we are deleting a file, src == 0, yet dest > 0.
The mentioned condition would then mean that a 0 byte count
would be added to the expected progress counter. However, after
every successful operation the got progress channel would be
updated so X deleted bytes would be added to the got progress channel,
yet were not added to the expected progress channel, hence causing
overflows in the overall progress reports.
=> fallback to counter.dest if the operation is a deletion

src/misc.go, src/stat.go
Fixes https://github.com/odeke-em/drive/issues/801.
Recompose and propagate encountered errors along with their
status/run-level codes, instead of just logging them.
* Exhibit:
```shell
$ drive stat goos-goarch && echo "success"; echo $?
stat: /goos-goarch err: remote path doesn't exist
9
```
=> stat: recompose and propagate error instead of just logging it

platform_packages.md
It is no longer required in debian testing, and possibly future releases.
=> apt-key changes in install notes

README.md, cmd/drive/main.go, src/misc.go, src/rc.go, src/rc_test.go, src/testdata/non-sectioned/.driverc, src/testdata/structured/.driverc
Fixes https://github.com/odeke-em/drive/issues/778.
Now allows you to restructure your .driverc separating
commands into sections and having different clauses.
Please note:
* You can put multiple commands in the same
section by using separator "/". See the rules at
https://github.com/odeke-em/namespace/blob/0ab79ba44f1328b1ec75ea985ad5c338ba3d56a6/ns.go#L3-L14
* Overwriting of command rules is
command_section > global
and
commandX_higher_line > commandX_lower_line
where lines are natural numbers that are ascending
* Exhibits:
This is a sample of a .driverc that I've just defined that has flexible
behavior in different sections.
```
id=true # Will be applied globally unless overwritten in a command
[global]
depth=10 # The depth to use if not defined
[pull/list]
depth=2 # The depth to be …
```
=> structured/sectioned .driverc configuration

cmd/drive/main.go, src/changes.go, src/commands.go, src/list.go, src/misc.go, src/rc.go, src/trash.go
Introduce DebugPrintf which can be used to give
contextual and debug information when things go wrong
and we need to observe them, when verbose or `DEBUG=true`
is set in the environment.
So far added debugging prints when parsing the .driverc file.
It prints out the:
[<FILE>:<FUNCTION>:<LINE_NUMBER>]
Prefix a drive invocation with `DEBUG=true`
```shell
$ DEBUG=true drive list share-testing/
[/Users/emmanuelodeke/go/src/github.com/odeke-em/drive/cmd/drive/main.go:main.discoverContext:1857]
contextPath: /Users/emmanuelodeke/emm.odeke@gmail.com/share-testing
[/Users/emmanuelodeke/go/src/github.com/odeke-em/drive/cmd/drive/main.go:main.discoverContext:1867]
driveRoot: "/Users/emmanuelodeke/emm.odeke@gmail.com" relToRoot: ""
[/Users/emmanuelodeke/go/src/github.com/odeke-em/drive/src/rc.go:githu …
```
=> command: introduce DebugPrintf

src/misc.go
Updates https://github.com/odeke-em/drive/pull/830.
Replace `DEBUG` with `DRIVE_DEBUG` to avoid clashes with other
programs that might need the `DEBUG` flag. `DRIVE_DEBUG` makes
it clear that this debug is only for drive.
=> replace DEBUG with DRIVE_DEBUG to avoid other program clashes

src/stat.go
Fixes https://github.com/odeke-em/drive/issues/783.
Ensures that for a directory, after decrementing the depth
by 1 in the parent's first pass that we at least operate on
passed in files instead of erraneously ending on that depth.
Traversal depth is meant for traversing directories/folders
and less on actual files.
This change leads us to conform to the proper behavior exhibited
by  `drive list`.
=> stat/md5: allow op on depth=0 for dir children

README.md, cmd/drive/main.go, src/commands.go, src/help.go, src/push.go, src/remote.go
Updates
https://github.com/odeke-em/drive/issues/28#issuecomment-84650909.
Allows one to customize the upload chunk size in bytes.
By default, the internal Google API's upload chunk size is 8MiB,
minimum chunk size is 256KiB. Any custom chunk size should be at
least 256KiB and also a multiple of 256KiB. Please see
https://godoc.org/google.golang.org/api/googleapi#pkg-constants.
* Exhibit:
```shell
$ drive push -upload-chunk-size 524288 demo.mp4
```
=> push: customizable upload chunk size

cmd/drive/main.go, src/clashes.go, src/pull.go, src/push.go
Fixes #836.
pull and push now have `-fix-mode` as an option to allow selecting
either "rename" or "trash" as the action to perform on fixing clashes.
```shell
$ drive push -fix-clashes -fix-mode trash a1 notes
$ drive pull -fix-clashes -fix-mode rename 2016 patents
```
=> pull/push: allow fix-mode selection

.travis.yml, README.md
Fixes #852.
Fixes #853.
Fixes #854.
Set the minimum Go version to 1.7.X.
Most of the Go versions below go1.7 are no longer even
supported. It is better to have the latest and greatest
with new features and more good things.
=> README: bump minimum Go version to 1.7.X

src/about.go
Updates
https://github.com/odeke-em/drive/pull/855#issuecomment-274678597.
Bump up the version by a minor point so that PPA builds can
be refreshed and built with at least go1.7.
=> version bump to v0.3.9.1 to refresh PPA builds

README.md, src/clashes.go, src/help.go
=> clashes: more notes about -fix-mode trash

src/stat.go, src/types.go
Resolves enhancement request #849
Adds a line showing the QuotaBytesUsed  to the output of the stat command          
e.g.
```
.
.
Bytes                     1166863
Size                      1.11MB
QuotaBytesUsed            1166863
DirType                   file
VersionNumber             5403
MimeType                  application/pdf
.
.
```
or for a high quality image:
```
.
.
Bytes                     1972143
Size                      1.88MB
QuotaBytesUsed            0
DirType                   file
VersionNumber             541010
MimeType                  image/jpeg
.
.
```
=> Add QuotaBytesUsed to stat output

cmd/drive/main.go, src/rc.go, src/rc_test.go, src/testdata/zero-values/.driverc
Fixes #902.
Add .driverc retrieval that was missing for commands:
* open
* md5sum
* stat
* index
* touch
* about
=> cmd/drive: add .driverc retrieval for missing commands

cmd/drive/main.go, src/help.go, src/rc.go, src/rc_test.go, src/testdata/zero-values/.driverc
Fixes #891.
Updates #906.
.driverc parsing should recognize more keys that are used
as command line arguments to different commands.
[Batcall to other contributors]: Please send PRs adding
missing keys, thank you!
=> .driverc parsing: recognize more CLI arguments/keys

src/remote.go
Ensure that nil is properly sent back after remote
change/file resolution. This regression was caused
by forgetting to send back that nil.
This regression was caused by PR
https://github.com/odeke-em/drive/pull/741.
The consequence of the bug was that trying to push
from non-existent folders would erraneously give
back
```shell
Resolving...
Everything is up-to-date.
```
since the remotesChan channel would get closed
after resolution without sending notifying
whoever was resolving that the file or parent didn't
exist remotely.
Fixes #933
=> changes: properly send back nil if no file is found

platform_packages.md
The PGP key of the previous PPA versions (xenial, yakkety, zesty) were based on RSA 2048.
The new security standards require 4096 bits key.
It also enables me to use the same PGP key between the PPA & the DR (Debian) repositories.
=> platform_packages.md: Updated PGP key for the new artful PPA matching the DR's one

.travis.yml, src/misc_test.go
Fix go vet feedback but change format specifiers for
functions from "%v" to "%p".
Shout-outs to @jean-christophe-manciot for helping
point this out that tips were failing on tip, without
any code changes.
=> src: fix go test + vet feedback

src/misc.go
A fallacy that some of us in the English speaking
world may have is that everyone uses products with English
but unfortunately that isn't the case as a Google Drive German
user has shown so add:
"Meine Ablage"
as a translation of
"My Drive"
Other translations are highly encouraged and welcomed, let's
crowd source them!
Updates https://github.com/odeke-em/drive/issues/1015
=> src/misc: add German equivalent of "My Drive"

src/trash.go
On `delete` option, the prompt shows `[Y/N]` when it should show `[Y/n]` as in \[2\] (or I believe so :sweat_smile:  )
\[1\]:
https://github.com/odeke-em/drive/blob/467def294e141ef4580b31749e95b2589d568dae/src/trash.go#L237
\[2\]:
https://github.com/odeke-em/drive/blob/313053b3dee5a2f553385e7e1b8a871e6193ceb0/src/misc.go#L324
=> Fix case in option in trash prompt

README.md
README: Fix grammar in Google Service Accounts section and add GSA link
Replaces #978 which was created by @ukd1
cc @odeke-em
=> Fixes #978

platform_packages.md
yaourt is discontinued and not advised to use anymore, so proposing yay as an example as the most functional aur helper as per Arch wiki.
this applies to all Arch based distros, too
also updating package name, link to aur and maintainer to reflect change in aur
=> update Arch Linux installation method

.travis.yml, README.md
Not sure what the plan is for supporting Golang <1.9, but it may just be easier to only support the last 3 versions (seems reasonable).
Libraries that this project depends on are not compatible with Golang
<1.9. Specifically, the build is failing on [golang/oauth2](https://github.com/golang/oauth2/blob/master/google/default.go#L38)
due to a type alias which is not supported in <1.9.
This commit:
- Removes support in Travis to fix builds failing on <1.9
- Update README.md to show support at >=1.9.x
=> Remove support for Go <1.9

src/misc.go
The .ipynb extension is typically used for Jupyter notebooks. Google's
Colaboratory editor is able to open/edit notebooks.
=> Add Colaboratory mime-type
