odeke-em/drive

README.md, changes.go, cmd/drive/main.go, push.go, remote.go, trash.go
Addresses https://github.com/odeke-em/drive/issues/9 providing functionality for both trashing and untrashing.
=> Trash untrash

README.md, cmd/drive/main.go, commands.go, list.go
Implemented the list method to address issue #10
=> list: method implemented

changes.go
This PR addresses  #22 and #27. The analysis and investigation as well as suggestion nudged by @fergald.
The idea is to limit the number of lookups as previously noted in the TODO.
=> changes: limit the number of active children lookups

config/config.go, src/changes.go, src/pull.go, src/push.go, src/types.go
This PR is meant to complete the conflict resolution mechanism by tracking file changes after a push or pull to help determine if there are actually conflicts. Any suggestions, ideas and feedback will be highly appreciated.
In case you would like to test it out:
```shell
$ go get github.com/odeke-em/drive/cmd/drive # Just in case you don't yet have it
$ cd $GOPATH/src/github.com/odeke-em/drive
$ git fetch --all && git pull origin memoization-by-indexing && git checkout memoization-by-indexing
$ go get github.com/odeke-em/drive/cmd/drive
```
=> Memoization by indexing

config/config.go
This PR addresses issue #68 in which .gd/indices path was being created relative to the current dir in context instead of relative to the root.
This patch also shaves a couple of bytes off Index serialized field names.
To apply this patch.
```shell
$ [ -d $GOPATH/src/github.com/odeke-em/drive ] || go get $GOPATH/src/github.com/odeke-em/drive/cmd/drive 
$ cd $GOPATH/src/github.com/odeke-em/drive
$ git fetch --all
$ git pull origin patch/indicesRoot && git checkout patch/indicesRoot
$ go get github.com/src/github.com/odeke-em/drive/cmd/drive
```
Then you can proceed with the testing.
=> config: load indicesAbsPath from root

src/misc.go, src/push.go, src/remote.go
This enables a common root to be created before
any mkdirAll attempts might be made in parallel.
This mitigates data races on trying to create common dirs.
This is a work in progress (not yet complete) to address issue #56.
=> finding common point of convergence

README.md, cmd/drive/main.go, src/help.go, src/move.go, src/remote.go
Move + Rename implemented
Work in progress to address issues #85 and #86
=> Move + Rename

README.md
=> Fix driveignore sample in README

cmd/drive/main.go, config/config.go, src/about.go, src/changes.go, src/commands.go, src/copy.go, src/diff.go, src/list.go, src/misc.go, src/publish.go, src/pull.go, src/push.go, src/share.go, src/stat.go, src/touch.go, src/trash.go
Using custom logger to log to stdout and stderr. This PR addresses issue https://github.com/odeke-em/drive/issues/95
=> logging: incorporated custom logger

src/diff.go
Work in progress to address issue #89.
=> diff: prettify output

src/changes.go
This PR addresses issue #180.
It makes it possible to always export exportable files (Google Docs + Sheets) even when their presence is consistent locally.
To apply the patch: in case you haven't already done so, please take a look at [applying patches](https://github.com/odeke-em/drive#applying-patches)
=> pull toggle exportable for mod when --exports specified

cmd/drive/main.go, src/list.go
This PR is a work in progress to address issue #187
=> list: listing shared untrashed possible

src/about.go
You forget to bump in sources :)
=> version bump to v0.2.2

src/misc.go
This PR addresses #215 by adding the mimeTypes for open-* document extensions.
=> open-office format mimeTypes added

README.md
Added so users don't have to search the issues pages to find this feature
=> Added to readme about -quiet and -no-prompt

src/changes.go, src/pull.go, src/push.go
This PR addresses two issues #262 and #261.
* This improves user experience in that the user can find out
what clashes affect them within sub-directories/folders for a
target dir/folder, during  a push or pull.
* Now using a plain hashmap to avoid problems with ASCII trie
clashing if encountering non-ASCII characters.
=> clashes: explore all clashes

config/config.go, src/fetch.go, src/pull.go, src/push.go, src/types.go
This PR is a work in progress to address issue https://github.com/odeke-em/drive/issues/106.
=> added boltdb for storing indices

src/misc.go, src/remote.go
* func customQuote : double-quoted, escape only \(backslash) and "(double quote)
* replace quote with customQuote in remote.go
=> add func customQuote

README.md
=> Add a link to list of MIME type short keys

src/pull.go, src/push.go
This PR allows for acknowledgement of pull + push errors in the dispatch loop.
It helps mitigate concerns raised in issue #304.
=> acknowledging pull+push errors in dispatch loop

src/misc.go
This PR addresses #326.
+ Fixed up type assertion for error received during
retry error checks.
+ Added OAuthErr amongst errors to be checked for retry.
=> retrier(expbackoff): fix err assert + add OAuthErr

src/changes.go, src/new.go
This PR addresses https://github.com/odeke-em/drive/issues/328.
=> ignore: properly ignore on change resolution

config/config.go
=> Fix path manipulation on Windows.

src/changes.go
=> ensure proper parent/dirname is passed in

src/pull.go
This PR addresses issue #390.
A bug in waiting for the parallelized completion of
error as well as change list appending meant that
whichever terminated first, mostly error list appending
did first since they'd be fewer errors than changelist values.
This meant that the results of combining matches would be ignored.
=> pull-matches: wait for of all `combine` results

src/push.go, src/remote.go
=> properly pass in "Debug" to retrier

README.md, cmd/drive/main.go, src/changes.go, src/diff.go, src/help.go, src/misc.go, src/push.go
This PR addresses issues https://github.com/odeke-em/drive/issues/93, https://github.com/odeke-em/drive/issues/410 and #409.
It allows for users to diff, pull or push to a desired depth
```shell
$ drive diff --depth 2 contexts diffs
```
```shell
$ drive push --depth -1 allMyFiles
```
```shell
$ drive pull --depth 3 photos
```
=> traversal depth added for diff + push + pull

src/stat.go, src/types.go
=> description field now retrieved

cmd/drive/main.go, src/help.go, src/remote.go
This PR addresses issues #420 and #419 and #421
=> fixed up help, version printing + gofmtd remote.go

src/stat.go
This PR addresses issue https://github.com/odeke-em/drive/issues/424
=> stat: respect traversal depth

src/changes.go, src/edit.go, src/fetch.go, src/init.go, src/misc.go, src/pull.go, src/push.go, src/share.go, src/trash.go
This PR addresses issue #460 
It makes sure to indicate to when the user has rejected the terms e.g on prompt to pull changes.
=> err indicated on rejection on prompt terms

README.md, cmd/drive/main.go, src/changes.go, src/commands.go, src/fetch.go, src/help.go, src/list.go, src/pull.go, src/remote.go, src/types.go
This PR addresses issue https://github.com/odeke-em/drive/issues/431 and allows for users to pull starred files
```shell
$ drive pull --starred
$ drive pull --starred --matches content
```
=> Pull starred

src/trash.go
Ensure that canPreview is passed to enable previewing.
=> trash: pass in canPreview

src/commands.go
Fixes #502.
This PR finishes up logic that was previously mistakenly ignored with the clause
```go
if opts.Quiet {
stdout = nil
}
```
and enforces it.
```shell
$ rm -rf "Emmanuel Odeke interview"* && drive pull --export pdf,rtf,txt --quiet  "Emmanuel Odeke interview" && ls -lrth | grep "Emmanuel Odeke"
Resolving...
Exported '/Users/emmanuelodeke/emm.odeke@gmail.com/Emmanuel Odeke interview' to '/Users/emmanuelodeke/emm.odeke@gmail.com/Emmanuel Odeke interview_exports/Emmanuel Odeke interview.txt'
Exported '/Users/emmanuelodeke/emm.odeke@gmail.com/Emmanuel Odeke interview' to '/Users/emmanuelodeke/emm.odeke@gmail.com/Emmanuel Odeke interview_exports/Emmanuel Odeke interview.rtf'
Exported '/Users/emmanuelodeke/emm.odeke@gmail.com/Emmanuel Odeke interview' to …
```
=> quiet: outstream if quiet is set

src/misc.go, src/pull.go, src/push.go
Refactored the slightly similar jobs rationers
in pull and push to use a common package.
=> pull/push: refactored the jobs rationer to use common package

src/remote.go
Fixes #538.
Ensures reqDoPage mimics the old behavior of not having
to pass back a nil file on non-existance of a file.
It allows for this behavior to be explicitly requested.
=> reqDoPage nilOnMatch setup

.travis.yml, src/misc_test.go
Tests started with src/misc.go
=> tests: misc started

src/remote.go
During a remote file resolve, if the file is not found, pass back
nil to the resolvedResults channel instead of skipping. This bug
was causing deeply nested and unsynced directories to not be
registered as pull/push worthy.
=> remote-file-resolve: pass back nil asap in file walk if fails.

README.md
=> README: add info about exponential backoff retry changing

src/commands.go
=> quiet: do not show progress bar if --quiet was set

src/about.go
You drive me nuts tagging a release and not bumping version lol.
=> bump version

platform_packages.md
Added steps to install from repo I've created. Will be updated 
in the same timeframe as the ppa and aur packages.
=> debian repo info

config/config.go, src/changes.go, src/fetch.go, src/publish.go, src/pull.go, src/push.go, src/rc.go, src/remote.go, src/stat.go, src/url.go
Updated some function signatures as well as named returns.
=> function signatures touched up

cmd/drive/main.go
Fixes https://github.com/odeke-em/drive/issues/685.
=> main/push: fixed no-clobber description

README.md
For the "Pull" chapter, I tried to make the text a bit more coherent. For the "Push" chapter I wanted to make clear that `true` is the default.
=> Clarify -ignore-checksum in README

src/remote.go
Fixes https://github.com/odeke-em/drive/issues/711.
+ Close open file descriptor that fills in the body right before an
upload.
+ Refactor the checks for whether we need a body, extracting that
code to a method `shouldUploadBody`.
The refactoring changes it to fix a legacy bug in which files
were unnecessarily opened even in cases where we later on
didn't need to upload the body.
This change should cut down file descriptor leaks and also
improve performance since during uploads:
* Firstly, we'll always close any open file.
* Secondly, we avoid unnecessarily opening files so we'll cut
down ulimit for file descriptor exhaustions as well as reduce
pressure on the garbage collector.
=> upload: close open file descriptor; refactor by extraction to method

src/errors.go, src/pull.go
=> pull: return a non-zero error when fixing clashes

platform_packages.md
Removing '$' symbol at the beginning of the line (command) - for easier copy&pasting.
=> Removing '$' symbol at the beginning of the line (command)

README.md, src/changes.go, src/dcrypto/dcrypto.go, src/dcrypto/v1/v1.go
These are very trivial, but we all like good spelling and hate bad compound words.
=> typos and compound words

README.md
Removing '$' symbol at the beginning of the line (command) - for easier copy&pasting (following the PR https://github.com/odeke-em/drive/pull/739).
=> Removing '$' symbol at the beginning of the line

src/move.go
Fixes https://github.com/odeke-em/drive/issues/826.
If a local path didn't exist to begin with, on remote renaming,
we shouldn't report the erraneous error. My usecase was manipulating
files that don't exist locally but do exist remotely.
=> rename: avoid err if local path never existed to begin with

src/about.go
=> about: bump version to v0.3.9!

README.md
I believe these are the actual forms supported by the tool today
=> Fix some inconsistencies in documentation

platform_packages.md
Fixes https://github.com/odeke-em/drive/issues/866
=> dirmngr is a requirement for Debian installation

platform_packages.md
Added guidelines about how to install the scripts included in drive-google on latest Ubuntu - Also reorganized the file
=> New PPA for latest UIbuntu

README.md
Also reorganized and cleaned up README.md
=> Update, reword and restructure README.md

README.md
=> readme: document push/pull -hidden

README.md, platform_packages.md
Hey Emmanuel,
How are you?
Here are the proposed modifications:
**README.md**:
- fixed an issue with "Verifying Checksums" title
- updated the automation scripts wiki URLs
**platform_packages.md**:
- updated the instructions to add the PPA for the scripts on latest Ubuntu
- added the instructions to add the DR (Debian Repository) for the scripts on latest Debian
=> README.md: Updated the automation scripts wiki URLs & added them on Debian

src/push.go
Previously, with multiple goroutines invoking remoteMkdirAll,
racyness manifested where-by:
Given a non-existent directory structure /A/B/C/D
* Goroutines [1, 2, 3, 4] ask remoteMkdirAll("/A/B/C/D")
none of them get back existence so simultaneously
* invoke remoteMkdirAll("/A/B/C")
[1, 2, 3, 4] simultaneously get back the same answer
and also invoke
* invoke remoteMkdirAll("/A/B")
[1, 2, 3, 4] simultaneously get back the same answer
and also invoke
* invoke remoteMkdirAll("/A")
[1, 2, 3, 4] simultaneously get back the same answer
and also invoke
* invoke remoteMkdirAll("/")
[1, 2, 3, 4] simultaneously get back the same answer
that "/" exists.
* [1, 2, 3, 4] now start creating "/A" simultaneously
* [1, 2, 3, 4] now start creating "/A/B" simultaneously
* [1, 2, 3, 4] now start creating …
=> src/push: a single goroutine exclusively invokes remoteMkdirAll

src/misc.go
=> src/misc: add French equivalent of "My Drive"

src/misc.go
Relates to #1015 
Spanish string:
Galician string:
=> Added galician and spanish names for "My Drive"

src/misc.go
=> Added marathi and hindi names for "My Drive"

src/misc.go
Relates to #1015
As a translation of "My Drive", Google Drive Indonesian user has shown "Drive Saya".
=> src/misc: add Indonesian equivalent of "My Drive"

README.md, cmd/drive/main.go, src/commands.go, src/help.go, src/push.go, src/remote.go
=> Implement `push` bandwidth limit 

src/misc.go
Relates to #1015 
Dutch string:
=> Translated My drive to Dutch

src/misc.go
=> misc: Add "My Drive" in Traditional Chinese

README.md
=> Revises README to clearly indicate need for drive context with push

config/config.go, src/misc.go
=> Add Vietnamese translation for 'My Drive'

src/misc.go
=> Add Bulgarian translation for 'My Drive'
